import React, { useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { X, Lightbulb, RotateCcw } from 'lucide-react';
import { RootState, store } from '../../store';
import { setTargetLetter, setCurrentHint, setSignMode } from '../../store/predictionSlice';
import { playSuccessSound, playErrorSound } from '../../utils/audio';
import { addXp, updateLetterStats } from '../../services/progressService';
import { CameraView } from '../Camera/CameraView';

interface SignItChallengeProps {
  targetLetter: string;
  onSuccess: (xpGained: number, timeToSignMs: number) => void;
  onDismiss: () => void;
}

export const SignItChallenge: React.FC<SignItChallengeProps> = ({
  targetLetter,
  onSuccess,
  onDismiss,
}) => {
  const dispatch = useDispatch();
  const [attempts, setAttempts] = useState(0);
  const [showHint, setShowHint] = useState(false);
  const [timeElapsed, setTimeElapsed] = useState(0);
  const [isSuccess, setIsSuccess] = useState(false);
  const [shakeError, setShakeError] = useState(false);
  const startTimeRef = useRef<number>(Date.now());
  const lastTextLengthRef = useRef<number>(0);

  const currentText = useSelector((state: RootState) => state.prediction.text);
  const currentHint = useSelector((state: RootState) => state.prediction.currentHint);

  // Whether the target is a digit (for dynamic header text).
  const isDigit = /^[0-9]$/.test(targetLetter);

  // Set target letter AND sign mode when challenge opens.
  // Numbers (0-9) require signMode='numbers' so the model restricts
  // predictions to digit classes instead of A-Z.
  useEffect(() => {
    dispatch(setTargetLetter(targetLetter));
    dispatch(setSignMode(isDigit ? 'numbers' : 'letters'));
    // Snapshot the current text length via the store so we only evaluate
    // NEW commits during this challenge — not pre-existing text from
    // earlier Live Practice sessions.  Read directly from the store
    // (not useSelector) to avoid a stale-closure / missing-dep issue.
    lastTextLengthRef.current = store.getState().prediction.text.length;
    startTimeRef.current = Date.now();
    return () => {
      dispatch(setTargetLetter(null));
      dispatch(setCurrentHint(null));
      // Restore default mode so other features aren't affected.
      dispatch(setSignMode('letters'));
    };
  }, [targetLetter, dispatch, isDigit]);

  // Timer — counts up every 100ms for motivational display (not punitive).
  useEffect(() => {
    if (isSuccess) return;
    const interval = setInterval(() => {
      setTimeElapsed(Math.floor((Date.now() - startTimeRef.current) / 100) / 10);
    }, 100);
    return () => clearInterval(interval);
  }, [isSuccess]);

  // Watch for commits (text length increases) and check if it matches target.
  useEffect(() => {
    if (isSuccess) return;

    const textLen = currentText.length;
    if (textLen > lastTextLengthRef.current) {
      const committedLetter = currentText[textLen - 1];
      lastTextLengthRef.current = textLen;

      // Check if the committed letter matches our target.
      if (committedLetter === targetLetter) {
        // SUCCESS!
        const timeToSignMs = Date.now() - startTimeRef.current;
        let xp = 5;
        if (timeToSignMs <= 1000) xp = 15;
        else if (timeToSignMs <= 2000) xp = 10;

        playSuccessSound();
        updateLetterStats(targetLetter, timeToSignMs);
        addXp(xp);
        setIsSuccess(true);

        // Close overlay after 800ms.
        setTimeout(() => {
          onSuccess(xp, timeToSignMs);
        }, 800);
      } else if (committedLetter && committedLetter !== targetLetter) {
        // Wrong letter committed.
        playErrorSound();
        setShakeError(true);
        setTimeout(() => setShakeError(false), 500);
        setAttempts((prev) => prev + 1);
      }
    }
  }, [currentText, targetLetter, isSuccess, onSuccess]);

  // Show hint button after 3 failed attempts.
  const canShowHint = attempts >= 3 && !showHint;

  const handleShowHint = () => {
    setShowHint(true);
    // The hint is already being generated by CameraView's hint logic when
    // targetLetter is set, so we just display currentHint from Redux.
  };

  const handleRetry = () => {
    setAttempts(0);
    setShowHint(false);
    startTimeRef.current = Date.now();
    setTimeElapsed(0);
    lastTextLengthRef.current = currentText.length;
  };

  return (
    <div className="fixed inset-0 z-[9000] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div
        className={`relative w-full max-w-2xl bg-white rounded-[2rem] sm:rounded-[3rem] border-4 border-teal-100 shadow-2xl overflow-hidden max-h-[90vh] flex flex-col ${
          shakeError ? 'animate-shake' : ''
        }`}
      >
        {/* Header */}
        <div className="bg-gradient-to-r from-teal-400 to-cyan-500 text-white px-5 sm:px-8 py-4 sm:py-6 flex items-center justify-between shrink-0">
          <div>
            <div className="text-xs sm:text-sm font-bold uppercase tracking-wider opacity-90">
              Sign this {isDigit ? 'number' : 'letter'}
            </div>
            <div className="text-4xl sm:text-5xl font-black mt-1">{targetLetter}</div>
          </div>

          <button
            onClick={onDismiss}
            className="w-11 h-11 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center transition-colors touch-target"
            title="Close challenge"
          >
            <X className="w-5 h-5 sm:w-6 sm:h-6" />
          </button>
        </div>

        {/* Camera feed */}
        <div className="relative aspect-video bg-slate-900 shrink-0">
          <CameraView />

          {/* Overlay UI on top of camera */}
          <div className="absolute inset-0 pointer-events-none flex flex-col items-center justify-center">
            {/* Target letter reminder */}
            <div className="bg-black/50 backdrop-blur-md text-white px-6 sm:px-8 py-3 sm:py-4 rounded-2xl border-2 border-white/30 shadow-xl">
              <div className="text-5xl sm:text-6xl font-black">{targetLetter}</div>
            </div>
          </div>

          {/* Success overlay */}
          {isSuccess && (
            <div className="absolute inset-0 bg-emerald-500/80 backdrop-blur-sm flex items-center justify-center animate-fade-in">
              <div className="text-white text-center">
                <div className="text-7xl sm:text-8xl mb-4">✓</div>
                <div className="text-3xl sm:text-4xl font-black">Perfect!</div>
              </div>
            </div>
          )}
        </div>

        {/* Stats bar */}
        <div className="bg-slate-50 px-4 sm:px-8 py-3 sm:py-4 flex items-center justify-between border-t-2 border-slate-100 shrink-0">
          <div className="flex items-center gap-4 sm:gap-6">
            {/* Attempts */}
            <div className="text-xs sm:text-sm">
              <span className="font-bold text-slate-500">Attempts:</span>
              <span className="ml-1 sm:ml-2 font-black text-slate-700">{attempts} / 3</span>
            </div>

            {/* Timer */}
            <div className="text-xs sm:text-sm">
              <span className="font-bold text-slate-500">Time:</span>
              <span className="ml-1 sm:ml-2 font-black text-slate-700">{timeElapsed.toFixed(1)}s</span>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2 sm:gap-3">
            {canShowHint && (
              <button
                onClick={handleShowHint}
                className="flex items-center gap-1.5 px-3 sm:px-5 py-2 sm:py-2.5 bg-amber-100 hover:bg-amber-200 text-amber-700 font-bold rounded-xl sm:rounded-2xl border-2 border-amber-200 transition-colors touch-target text-xs sm:text-sm"
              >
                <Lightbulb className="w-4 h-4" />
                <span className="hidden sm:inline">Show </span>Hint
              </button>
            )}

            {attempts >= 1 && (
              <button
                onClick={handleRetry}
                className="flex items-center gap-1.5 px-3 sm:px-5 py-2 sm:py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded-xl sm:rounded-2xl border-2 border-slate-200 transition-colors touch-target text-xs sm:text-sm"
              >
                <RotateCcw className="w-4 h-4" />
                Retry
              </button>
            )}
          </div>
        </div>

        {/* Hint display */}
        {showHint && currentHint && (
          <div className="bg-amber-50 border-t-2 border-amber-200 px-5 sm:px-8 py-3 sm:py-4 shrink-0">
            <div className="flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
              <p className="text-amber-900 font-bold text-sm sm:text-base">{currentHint}</p>
            </div>
          </div>
        )}

        {/* Instruction */}
        {!isSuccess && (
          <div className="bg-teal-50 border-t-2 border-teal-100 px-5 sm:px-8 py-3 sm:py-4 text-center shrink-0">
            <p className="text-teal-700 font-bold text-xs sm:text-sm">
              Hold up your hand and sign <strong>{targetLetter}</strong>. The camera is watching!
            </p>
          </div>
        )}
      </div>

      {/* Inline styles for shake animation */}
      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          10%, 30%, 50%, 70%, 90% { transform: translateX(-8px); }
          20%, 40%, 60%, 80% { transform: translateX(8px); }
        }
        .animate-shake {
          animation: shake 0.5s ease-in-out;
        }
        @keyframes fade-in {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        .animate-fade-in {
          animation: fade-in 0.3s ease-out;
        }
      `}</style>
    </div>
  );
};
